language: python
python:
  - "3.6"
install:
  - 'pip install pipenv'
  - 'pipenv sync'

script: 'python -m pytest --cov=pyblizzard tests --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'